stages:
  - build
  # - test-jest
  - test-cypress

build job:
  image: node:14
  stage: build
  script:
    - cd serverless/
    - npm install
    - npm run build  

# test jest job:
#   image: node:14
#   stage: test-jest
#   script:
#     - cd serverless/
#     - npm install
#     - npm test

test cypress job:
  image: cypress/base:14.16.0
  stage: test-cypress
  script:
    - cd serverless/
    - npm ci --prefer-offline
    - npm start &
    - npx cypress run  