stages:
  - build
  - test-cypress

build job:
  image: node:14
  stage: build
  script:
    - cd serverless/
    - npm install
    - npm run build  

test cypress job:
  image: cypress/base:14.16.0
  stage: test-cypress
  script:
    - cd serverless/
    - nohup npm run dev &
    - npm ci --prefer-offline
    - npm start &
    - npx cypress run  