image: node:14.17.3

stages:
  - build
  - test

cache:
  paths:
    - node_modules/  

build job:
  stage: build
  script:
    - rm -rf build
    - cd serverless/
    - CI=false npm install
    - npm install
    - npm test
  artifacts:
    paths:
      - serverless/

