image: node:14
stages:
  - build

build job:
  stage: build
  script:
    - cat $CI_PROJECT_DIR
    - cd /builds/c1847017/zc2030/serverless/
    - npm install
  artifacts:
    paths:
      - serverless/

