stages:
  - build
  - test

build job:
  image: node:latest
  stage: build
  script:
    - cd /builds/c1847017/zc2030/serverless/
    - npm install
  artifacts:
    paths:
      - serverless/

cypress-test job:
  stage: test
  script:
    - cd /builds/c1847017/zc2030/serverless/
    - npm install
    - npx cypress run      

