stages:
  - build
  - test

build job:
  stage: build
  image: node:14
  script:
    - cd serverless/
    - npm install
    - npm run build

deploy job:
  stage: test
  image: node:14
  script:
    - cd serverless/
    - npm install
    - npm test