stages:
  - build
  - test-jest
  - test-cypress

build job:
  stage: build
  script:
    - cd serverless/
    - npm install

cypress-test job:
  stage: test-cypress
  script:
    - npx cypress run

jest-test job:
  stage: test-jest
  script:
    - npm test   