stages:
  - build
  - test

build job:
  image: node:14
  stage: build
  script:
    - cd serverless/
    - npm install
    - npm run build

test jest job:
  image: node:14
  stage: test
  script:
    - cd serverless/
    - npm install
    - npm test

test cypress job:
  image: node:14
  stage: test
  script:
    - cd serverless/
    - npm install
    - npx cypress run    