image: node:14.17.3

stages:
  - build
  - test

cache:
  paths:
    - node_modules/  

build job:
  stage: build
  script:
    - rm -rf build
    - cd serverless/
    - CI=false npm install
    - npm install
    - npm test
  artifacts:
    paths:
      - serverless/

# cypress-test job:
#   image: cypress/base:14.16.0
#   stage: test
#   cache:
#     paths:
#       - .npm
#       - cache/Cypress
#   script:
#     - npm ci --prefer-offline
#     - npm start &
#     - npx cypress run 

