build job:
  image: node:14
  script:
    - cd serverless/
    - npm install

cypress-test job:
  script:
    - cd serverless/
    - npm install
    - npx cypress run

jest-test job:
  script:
    - cd serverless/
    - npm install
    - npm test
    - npx cypress run    