variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  
stages:
  - build
  - test

build job:
  image: node:latest
  stage: build
  script:
    - cd /builds/c1847017/zc2030/serverless/
    - npm install
    - npm test
  artifacts:
    paths:
      - serverless/

# cypress-test job:
#   image: cypress/base:14.16.0
#   stage: test
#   cache:
#     paths:
#       - .npm
#       - cache/Cypress
#   script:
#     - npm ci --prefer-offline
#     - npm start &
#     - npx cypress run 

