stages:
  - build

build job:
  stage: build
  image: node:14
  script:
    - cd serverless/
    - npm install

cypress-test job:
  stage: .post
  script:
    - npx cypress run

jest-test job:
  stage: .post
  script:
    - npm test   