stages:
  -build
  -run

build:
  stage: build
  image: node:14

  script:
    -npm install
    -npm run build

deploy job:
  stage: run
  image: node:14

  script:
    -npm install
    -npm run dev

