stages:
  - test
  - build

test project:
  stage: test
  image: 14
  script:
    - npm install
    - npm test
    - npx cypress run

build project:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
    - npm run dev